on:
  push:
    branches:
      - master
  create:
    tags:
      - v*.*.*

jobs:
  release: # job_id
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go latest
      uses: actions/setup-go@v1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Build
      env:
        GO111MODULE: on
        GOPATH: /home/runner/work/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        C_KEY: ${{ secrets.C_KEY }}
        REF: ${{ github.ref }}
        CS_KEY: ${{ secrets.CS_KEY }}

      run: |
        export CREATE_EVENT_REF_TYPE=$(jq --raw-output .ref_type "$GITHUB_EVENT_PATH")
        go get -t -v ./...
        go get -u github.com/mitchellh/gox
        go get -u github.com/tcnksm/ghr
        $GOPATH/bin/gox -osarch "freebsd/arm linux/386 linux/amd64 linux/arm linux/mips64le linux/mips64 linux/mipsle linux/mips linux/s390x netbsd/386 netbsd/amd64 netbsd/arm openbsd/386 openbsd/amd64 windows/386 windows/amd64 darwin/amd64" -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" -ldflags="-X github.com/syui/twg/oauth.ckey=${C_KEY} -X github.com/syui/twg/oauth.cskey=${CS_KEY}"
        $GOPATH/bin/ghr --username syui --token ${GITHUB_TOKEN} --replace --debug ${REF##*/} dist/

